dist: xenial
language: python

python:
  - "3.6.7"

env:
  global:
    - CC_TEST_REPORTER_ID=b12ab7d502152c8ad1222b8bd574a39caee67cc4e939d062ebd2879c8fc4ebc1

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

addons:
  postgresql: "9.4"


before_script:
  - psql -c 'create database test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# run tests

script:
  - python manage.py makemigrations authentication
  - python manage.py migrate authentication
  - coverage run --source= manage.py test
  - coverage report

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - coverallslanguage: python
  - coveralls